import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Turnos app",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: '/favicon-dark.svg',
        media: '(prefers-color-scheme: dark)',
      },
      {
        url: '/favicon-light.svg',
        media: '(prefers-color-scheme: light)',
      },
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} dark grid grid-rows-[80px,1fr,30px] min-h-screen`}
      >
        <header>
          <Navbar />
        </header>
        <main>
          {children}
        </main>
        <footer>
          <div
            className="container text-center"
          >
            <p>
              © {new Date().getFullYear()} - Turnos app
            </p>
          </div>
        </footer>
        <Toaster />
      </body>
    </html>
  );
}
